// <auto-generated />
using System;
using FlexiToggle.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlexiToggle.Api.Migrations
{
    [DbContext(typeof(FlexiToggleContext))]
    [Migration("20251113150013_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("FlexiToggle.Api.Models.ActivationStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Constraints")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureFlagEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagEnvironmentId");

                    b.ToTable("ActivationStrategies");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Environments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Ambiente de desenvolvimento",
                            IsActive = true,
                            Key = "development",
                            Name = "Development",
                            ProjectId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Ambiente de homologação",
                            IsActive = true,
                            Key = "staging",
                            Name = "Staging",
                            ProjectId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Ambiente de produção",
                            IsActive = true,
                            Key = "production",
                            Name = "Production",
                            ProjectId = 1,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1420),
                            CreatedById = 1,
                            Description = "Ativar nova interface do usuário",
                            IsArchived = false,
                            Key = "new_ui",
                            Name = "Nova Interface",
                            ProjectId = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1420)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1420),
                            CreatedById = 1,
                            Description = "Habilitar novo sistema de pagamento",
                            IsArchived = false,
                            Key = "payment_system",
                            Name = "Sistema de Pagamento",
                            ProjectId = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1420)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1430),
                            CreatedById = 1,
                            Description = "Limite de tamanho para upload de arquivos",
                            IsArchived = false,
                            Key = "upload_limit",
                            Name = "Limite de Upload",
                            ProjectId = 1,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1430)
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("FeatureFlagId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("FeatureFlagEnvironments");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            DefaultValue = "true",
                            EnvironmentId = 1,
                            FeatureFlagId = 10,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1450)
                        },
                        new
                        {
                            Id = 11,
                            DefaultValue = "true",
                            EnvironmentId = 2,
                            FeatureFlagId = 10,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1450)
                        },
                        new
                        {
                            Id = 12,
                            DefaultValue = "false",
                            EnvironmentId = 3,
                            FeatureFlagId = 10,
                            IsEnabled = false,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1450)
                        },
                        new
                        {
                            Id = 13,
                            DefaultValue = "true",
                            EnvironmentId = 1,
                            FeatureFlagId = 11,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1460)
                        },
                        new
                        {
                            Id = 14,
                            DefaultValue = "false",
                            EnvironmentId = 2,
                            FeatureFlagId = 11,
                            IsEnabled = false,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1460)
                        },
                        new
                        {
                            Id = 15,
                            DefaultValue = "false",
                            EnvironmentId = 3,
                            FeatureFlagId = 11,
                            IsEnabled = false,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1460)
                        },
                        new
                        {
                            Id = 16,
                            DefaultValue = "100",
                            EnvironmentId = 1,
                            FeatureFlagId = 12,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1460)
                        },
                        new
                        {
                            Id = 17,
                            DefaultValue = "50",
                            EnvironmentId = 2,
                            FeatureFlagId = 12,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1460)
                        },
                        new
                        {
                            Id = 18,
                            DefaultValue = "25",
                            EnvironmentId = 3,
                            FeatureFlagId = 12,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1460)
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("FeatureFlagId");

                    b.HasIndex("UserId");

                    b.ToTable("FeatureFlagEvents");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageResponseTime")
                        .HasColumnType("REAL");

                    b.Property<int>("DisabledCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnabledCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Evaluations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureFlagEnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagEnvironmentId", "Timestamp");

                    b.ToTable("FeatureFlagMetrics");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagTag", b =>
                {
                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeatureFlagId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FeatureFlagTags");

                    b.HasData(
                        new
                        {
                            FeatureFlagId = 10,
                            TagId = 10
                        },
                        new
                        {
                            FeatureFlagId = 11,
                            TagId = 11
                        },
                        new
                        {
                            FeatureFlagId = 12,
                            TagId = 12
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1220),
                            CreatedById = 1,
                            Description = "Projeto de demonstração do FeatureHub",
                            IsActive = true,
                            Key = "demo",
                            Name = "Demo Project",
                            UpdatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1220)
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoinedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1250),
                            ProjectId = 1,
                            Role = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Color = "#3b82f6",
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1500),
                            Name = "frontend",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 11,
                            Color = "#10b981",
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1500),
                            Name = "backend",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 12,
                            Color = "#f59e0b",
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(1500),
                            Name = "experimental",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 13, 15, 0, 12, 722, DateTimeKind.Utc).AddTicks(610),
                            Email = "admin@featurehub.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = "$2a$11$bATxdwEVki0CUFH5lVc8hOIBuBedn2./ygXo8oqrq3/U/Q.J5ADmq",
                            Role = 0
                        });
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Events")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Secret")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.WebhookDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebhookId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WebhookId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebhookId");

                    b.HasIndex("WebhookId1");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.ActivationStrategy", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.FeatureFlagEnvironment", "FeatureFlagEnvironment")
                        .WithMany("ActivationStrategies")
                        .HasForeignKey("FeatureFlagEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlagEnvironment");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.ApiKey", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.Environment", "Environment")
                        .WithMany("ApiKeys")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Environment", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.Project", "Project")
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlag", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.Project", "Project")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagEnvironment", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.Environment", "Environment")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.FeatureFlag", "FeatureFlag")
                        .WithMany("Environments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Environment");

                    b.Navigation("FeatureFlag");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagEvent", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlexiToggle.Api.Models.FeatureFlag", "FeatureFlag")
                        .WithMany("Events")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Environment");

                    b.Navigation("FeatureFlag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagMetric", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.FeatureFlagEnvironment", "FeatureFlagEnvironment")
                        .WithMany("Metrics")
                        .HasForeignKey("FeatureFlagEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlagEnvironment");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagTag", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.FeatureFlag", "FeatureFlag")
                        .WithMany("Tags")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.Tag", "Tag")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Project", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.ProjectMember", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Tag", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Webhook", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.WebhookDelivery", b =>
                {
                    b.HasOne("FlexiToggle.Api.Models.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiToggle.Api.Models.Webhook", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookId1");

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Environment", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("FeatureFlags");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlag", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Events");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.FeatureFlagEnvironment", b =>
                {
                    b.Navigation("ActivationStrategies");

                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Project", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("FeatureFlags");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Tag", b =>
                {
                    b.Navigation("FeatureFlags");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("ProjectMemberships");
                });

            modelBuilder.Entity("FlexiToggle.Api.Models.Webhook", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
